### ISSUE TITLE
Issue finding clockout element

### ISSUE THREAD

**Issue by kendallm** [Shaun-Regenbaum/OneUSGAutomaticClock#8]
Running the script successfully clocks out, but the script fails to exit correctly due to not finding an expected element on the page after clocking out.

```
Traceback (most recent call last):
  File "/Users/kendall/Development/OneUSGAutomaticClock/clock_manager.py", line 297, in <module>
    for i in range(15):
  File "/Users/kendall/Development/OneUSGAutomaticClock/clock_manager.py", line 131, in clockHoursOut
    WAIT.until(lambda DRIVER: DRIVER.find_element_by_id(
TypeError: 'WebElement' object is not subscriptable
```

**Comment by kendallm** [comment]
Updated my PR to fix this issue. Looks like the problem was find_element_by_id returns a single WebElement, not a list. This makes sense because id tags should be unique on a page.
